config/routes.rb
Rails.application.routes.draw do

  root 'static_pages#home'
  get     'about'    => 'static_pages#about'
  get     'contact'  => 'static_pages#contact'

  get     'login'    => 'sessions#new'
  post    'login'    => 'sessions#create'
  delete  'logout'   => 'sessions#destroy'

  resources :artworks

end

app/models/artwork.rb
class Artwork < ActiveRecord::Base
  belongs_to :category

  mount_uploader :image, ArtworkImagesUploader

  validate :width_height_presence_mutuality
  validate :image_size

  validates :width, :height, numericality: true, allow_blank: true
  validates :name, presence: true
  validates :image, presence: {message: "file to upload is needed."}

  private

    def width_height_presence_mutuality
      if width && height
        return
      elsif width
        errors.add(:height, "cannot be empty with a width given.")
      elsif height
        errors.add(:width, "cannot be empty with a height given.")
      end
    end

    def image_size
      if image.size > 5.megabytes
        errors.add(:image, "should be less than 5MB")
      end
    end

end

app/controllers/artworks_controller.rb
class ArtworksController < ApplicationController
  before_action :set_artwork, only: [:show, :edit, :update, :destroy]
  before_action :set_pagination, only: [:index, :new, :edit, :create, :update]
  before_action :authorize_admin, except: [:index, :show]
  # GET /artworks
  def index
  end

  # GET /artworks/1
  # GET /artworks/1.json
  def show
  end

  # GET /artworks/new
  def new
    @artwork = Artwork.new
  end

  # GET /artworks/1/edit
  def edit
  end

  # POST /artworks
  def create
    @artwork = Artwork.new(artwork_params)
    if @artwork.save
      redirect_to edit_artwork_path(@artwork.id), notice: 'New art piece created.'
    else
      render :new
    end
  end

  # PATCH/PUT /artworks/1
  def update
    if @artwork.update(artwork_params)
      redirect_to edit_artwork_path, notice: 'Artwork was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /artworks/1
  def destroy
    @artwork.destroy
    redirect_to new_artwork_url, notice: 'Artwork was successfully destroyed.'
  end

  private
    def authorize_admin
      redirect_to root_path unless is_admin?
    end

    def set_artwork
      @artwork = Artwork.find(params[:id])
    end

  def set_pagination
    @artworks = Artwork.paginate(:page => params[:page], :per_page => 6)
  end

    def artwork_params
      params.require(:artwork).permit(:category_id, :name, :description, :width, :height, :sold, :price, :image)
    end
end

app/helpers/artworks_helper.rb
module ArtworksHelper

  def thumb_link artwork
    link_to image_tag(artwork.image.thumb.url), artwork
  end

  def art_img_link artwork
    link_to image_tag(artwork.image_url), artwork
  end

end

app/views/artworks/_artwork.html.slim
= cycle tr, ""
    td
      = link_to image_tag(artwork.image), artwork

app/views/artworks/_form.html.slim
#management_container
  #management_form
    = form_for(@artwork, html: {multipart: true}) do |f|

      = render 'shared/error_messages'

      .form-group
        = f.label :name
        br
        = f.text_field :name, class: 'form-control'

      .form-group
        = f.label :description
        br
        = f.text_area :description, class: 'form-control'

      .form-group
        = f.label :width
        br
        = f.text_field :width, size: 6, maxlength: 6, class: 'form-control'

      .form-group
        = f.label :height
        br
        = f.text_field :height, size: 6, maxlength: 6, class: 'form-control'

      .form-group
        = f.label :category_id
        br
        = f.collection_select(:category_id, Category.all, :id, :name, {include_blank: true}, {class: 'form-control'})

      .form-group
        = f.label :sold
        br
        = f.check_box :sold, class: 'checkbox'

      .form-group
        = f.label :price
        br
        = f.text_field :price, class: 'form-control'

      .form-group
        = f.label :image
        br
        = f.file_field :image, accept: 'image/jpeg,image/gif,image/png', class: 'form-control'

      .actions
        = f.submit class: 'btn btn-default'


        = f.button "Delete", name:'_method', value: 'delete', disabled: !@artwork.id, data: {confirm: "Are you sure you would like to delete this art piece?"}, class: 'btn btn-default'

  #artwork_manage_list
    table
      - @artworks.each do |artwork|
        tr
          td
            = link_to image_tag(artwork.image.thumb.url), edit_artwork_path(artwork.id)

    = will_paginate @artworks, params: {action: 'new' }


javascript:
  $('#artwork_image').bind('change', function() {
    var size_in_megabytes = this.files[0].size/1024/1024;
    if (size_in_megabytes > 5) {
      alert('Maximum file size is 5MB. Please choose a smaller file.');
    }
  });

app/views/artworks/edit.html.slim
-provide(:title,'- Update artwork')
h1 Editing artwork

= render 'form'

/= link_to 'Show', @artwork  | |
/= link_to 'Back', artworks_path

app/views/artworks/index.html.slim
h1 Artwork

table
  - @artworks.each_slice(2) do |slice|
    tr
      - slice.each do |artwork|
        td
          = thumb_link artwork

nav
  = will_paginate @artworks

app/views/artworks/new.html.slim
-provide(:title, '- New artwork')
h1 New artwork

= render 'form'

app/views/artworks/show.html.slim
h2 "#{@artwork.name}"

#preview
  = art_img_link @artwork
p
  - if(@artwork.width && @artwork.height)
    |#{@artwork.width}" x #{@artwork.height}"
  br
  br

  = @artwork.description

  br
  br
  -unless(@artwork.sold || @artwork.price <= 0)
    | $#{'%.02f' % @artwork.price}
/  <strong>Category:</strong>
/  <%= @artwork.category %>
/</p>
/
/<p>
/  <strong>Name:</strong>
/  <%= @artwork.name %>
/</p>
/
/<p>
/  <strong>Description:</strong>
/  <%= @artwork.description %>
/</p>
/
/<p>
/  <strong>Width:</strong>
/  <%= @artwork.width %>
/</p>
/
/<p>
/  <strong>Height:</strong>
/  <%= @artwork.height %>
/</p>
/
/<p>
/  <strong>Sold:</strong>
/  <%= @artwork.sold %>
/</p>
/
/<p>
/  <strong>Price:</strong>
/  <%= @artwork.price %>
/</p>
/
/<%= link_to 'Edit', edit_artwork_path(@artwork) %> |
span.image_nav
  = link_to 'Back', :back